--- 
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    apt: 
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to restart webserver
    service: 
       name: apache2
       state: restarted
    when: ansible_os_family=="Debian"


  - name: i want to install webserver on redahat
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
    

  - name: i want to start webserver
    service:
       name: httpd
       state: started
    when: ansible_os_family=="RedHat"